version: '3.9'

services:
  backend:
    build: ./back
    container_name: credix-case-backend
    restart: always
    volumes:
      - ./back:/app
    ports:
      - '8000:8000'
    env_file:
      - .env
    command:
      [
        'sh',
        '-c',
        'python manage.py migrate && gunicorn --bind 0.0.0.0:8000 core.wsgi:application',
      ]

volumes:
  postgres_data:
